artifcats_root: artifcats


data_ingestion:
  root_dir: artifcats/data_ingestion
  source_url: https://github.com/junayed/demodatasets/raw/main/Concretecrack.zip
  local_data_file: artifcats/data_ingestion/data.zip
  unzip_dir: artifcats/data_ingestion


prepare_base_model:
  root_dir: artifcats/prepare_base_model
  base_model_path: artifcats/prepare_base_model/base_model.h5
  updated_base_model_path: artifcats/prepare_base_model/base_model_updated.h5